services:
  - type: web
    name: leee-discord-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 8080
